#!/bin/bash
# deploy-local.sh - Deploy contracts to local Anvil node
# Usage: ./deploy-local.sh [--no-anvil]
#
# Options:
#   --no-anvil    Skip starting Anvil (assumes it's already running)
#
# This script:
# 1. Starts Anvil (local Ethereum node) if not --no-anvil
# 2. Deploys all contracts using DeployLocal.s.sol
# 3. Outputs deployed addresses to .env.local

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONTRACTS_DIR="$(dirname "$SCRIPT_DIR")"
ROOT_DIR="$(dirname "$CONTRACTS_DIR")"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Configuration
ANVIL_PORT=${ANVIL_PORT:-8545}
ANVIL_RPC_URL="http://localhost:$ANVIL_PORT"
ANVIL_PID_FILE="/tmp/anvil-thesis.pid"

# Default deployer private key (Anvil account 0)
PRIVATE_KEY=${PRIVATE_KEY:-"0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"}

# Parse arguments
START_ANVIL=true
for arg in "$@"; do
    case $arg in
        --no-anvil)
            START_ANVIL=false
            shift
            ;;
    esac
done

echo -e "${GREEN}=== Thesis Local Deployment ===${NC}"
echo "Contracts directory: $CONTRACTS_DIR"
echo "RPC URL: $ANVIL_RPC_URL"

# Function to check if Anvil is running
check_anvil() {
    curl -s -X POST -H "Content-Type: application/json" \
        --data '{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":1}' \
        "$ANVIL_RPC_URL" > /dev/null 2>&1
}

# Function to start Anvil
start_anvil() {
    echo -e "${YELLOW}Starting Anvil...${NC}"
    
    # Kill any existing Anvil process
    if [ -f "$ANVIL_PID_FILE" ]; then
        OLD_PID=$(cat "$ANVIL_PID_FILE")
        if kill -0 "$OLD_PID" 2>/dev/null; then
            echo "Stopping existing Anvil process (PID: $OLD_PID)"
            kill "$OLD_PID" 2>/dev/null || true
            sleep 1
        fi
        rm -f "$ANVIL_PID_FILE"
    fi
    
    # Start Anvil in background
    anvil --port "$ANVIL_PORT" \
          --block-time 1 \
          --accounts 10 \
          --balance 10000 \
          > /tmp/anvil-thesis.log 2>&1 &
    
    ANVIL_PID=$!
    echo "$ANVIL_PID" > "$ANVIL_PID_FILE"
    
    # Wait for Anvil to be ready
    echo "Waiting for Anvil to start..."
    for i in {1..30}; do
        if check_anvil; then
            echo -e "${GREEN}Anvil started successfully (PID: $ANVIL_PID)${NC}"
            return 0
        fi
        sleep 0.5
    done
    
    echo -e "${RED}Failed to start Anvil${NC}"
    cat /tmp/anvil-thesis.log
    exit 1
}

# Function to stop Anvil
stop_anvil() {
    if [ -f "$ANVIL_PID_FILE" ]; then
        PID=$(cat "$ANVIL_PID_FILE")
        if kill -0 "$PID" 2>/dev/null; then
            echo "Stopping Anvil (PID: $PID)"
            kill "$PID" 2>/dev/null || true
        fi
        rm -f "$ANVIL_PID_FILE"
    fi
}

# Start Anvil if requested
if [ "$START_ANVIL" = true ]; then
    start_anvil
else
    if ! check_anvil; then
        echo -e "${RED}Error: Anvil is not running at $ANVIL_RPC_URL${NC}"
        echo "Start Anvil manually or run without --no-anvil"
        exit 1
    fi
    echo -e "${GREEN}Using existing Anvil instance${NC}"
fi

# Deploy contracts
echo -e "${YELLOW}Deploying contracts...${NC}"
cd "$CONTRACTS_DIR"

# Run deployment script and capture output
DEPLOY_OUTPUT=$(forge script script/DeployLocal.s.sol:DeployLocal \
    --rpc-url "$ANVIL_RPC_URL" \
    --broadcast \
    --private-key "$PRIVATE_KEY" \
    2>&1)

echo "$DEPLOY_OUTPUT"

# Extract addresses from deployment output
extract_address() {
    local pattern="$1"
    echo "$DEPLOY_OUTPUT" | grep -oP "${pattern}=\K0x[a-fA-F0-9]{40}" | head -1
}

USDC_ADDRESS=$(extract_address "USDC_ADDRESS")
CTF_ADDRESS=$(extract_address "CTF_ADDRESS")
EXCHANGE_ADDRESS=$(extract_address "EXCHANGE_ADDRESS")
VAULT_ADDRESS=$(extract_address "VAULT_ADDRESS")
MARKET_FACTORY_ADDRESS=$(extract_address "MARKET_FACTORY_ADDRESS")

# Validate addresses were extracted
if [ -z "$USDC_ADDRESS" ] || [ -z "$CTF_ADDRESS" ] || [ -z "$EXCHANGE_ADDRESS" ] || [ -z "$VAULT_ADDRESS" ] || [ -z "$MARKET_FACTORY_ADDRESS" ]; then
    echo -e "${RED}Error: Failed to extract all contract addresses${NC}"
    echo "USDC_ADDRESS: $USDC_ADDRESS"
    echo "CTF_ADDRESS: $CTF_ADDRESS"
    echo "EXCHANGE_ADDRESS: $EXCHANGE_ADDRESS"
    echo "VAULT_ADDRESS: $VAULT_ADDRESS"
    echo "MARKET_FACTORY_ADDRESS: $MARKET_FACTORY_ADDRESS"
    exit 1
fi

# Create .env.local file in contracts directory
ENV_LOCAL_FILE="$CONTRACTS_DIR/.env.local"
cat > "$ENV_LOCAL_FILE" << EOF
# Local Development Environment Configuration
# Generated by deploy-local.sh on $(date -Iseconds)
# DO NOT COMMIT THIS FILE

# Network Configuration
CHAIN_ID=31337
RPC_URL=$ANVIL_RPC_URL

# Contract Addresses
USDC_ADDRESS=$USDC_ADDRESS
CTF_ADDRESS=$CTF_ADDRESS
EXCHANGE_ADDRESS=$EXCHANGE_ADDRESS
VAULT_ADDRESS=$VAULT_ADDRESS
MARKET_FACTORY_ADDRESS=$MARKET_FACTORY_ADDRESS

# Operator Configuration (Anvil account 0)
OPERATOR_ADDRESS=0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266
OPERATOR_PRIVATE_KEY=$PRIVATE_KEY
EOF

echo -e "${GREEN}Created $ENV_LOCAL_FILE${NC}"

# Create .env.local for backend
BACKEND_ENV_FILE="$ROOT_DIR/packages/backend/.env.local"
cat > "$BACKEND_ENV_FILE" << EOF
# Local Development Environment Configuration
# Generated by deploy-local.sh on $(date -Iseconds)
# DO NOT COMMIT THIS FILE

# Server Configuration
PORT=3001
HOST=localhost

# Network Configuration
CHAIN_ID=31337
RPC_URL=$ANVIL_RPC_URL

# Contract Addresses
USDC_ADDRESS=$USDC_ADDRESS
CTF_ADDRESS=$CTF_ADDRESS
EXCHANGE_ADDRESS=$EXCHANGE_ADDRESS
VAULT_ADDRESS=$VAULT_ADDRESS
MARKET_FACTORY_ADDRESS=$MARKET_FACTORY_ADDRESS

# Operator Configuration (Anvil account 0)
OPERATOR_ADDRESS=0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266
OPERATOR_PRIVATE_KEY=$PRIVATE_KEY
EOF

echo -e "${GREEN}Created $BACKEND_ENV_FILE${NC}"

# Create .env.local for frontend
FRONTEND_ENV_FILE="$ROOT_DIR/packages/frontend/.env.local"
cat > "$FRONTEND_ENV_FILE" << EOF
# Local Development Environment Configuration
# Generated by deploy-local.sh on $(date -Iseconds)
# DO NOT COMMIT THIS FILE

# Network Configuration
VITE_CHAIN_ID=31337
VITE_RPC_URL=$ANVIL_RPC_URL

# Contract Addresses
VITE_USDC_ADDRESS=$USDC_ADDRESS
VITE_CTF_ADDRESS=$CTF_ADDRESS
VITE_EXCHANGE_ADDRESS=$EXCHANGE_ADDRESS
VITE_VAULT_ADDRESS=$VAULT_ADDRESS
VITE_MARKET_FACTORY_ADDRESS=$MARKET_FACTORY_ADDRESS

# WalletConnect (optional for local dev)
VITE_WALLETCONNECT_PROJECT_ID=
EOF

echo -e "${GREEN}Created $FRONTEND_ENV_FILE${NC}"

# Summary
echo ""
echo -e "${GREEN}=== Deployment Complete ===${NC}"
echo ""
echo "Contract Addresses:"
echo "  USDC:           $USDC_ADDRESS"
echo "  ConditionalTokens: $CTF_ADDRESS"
echo "  CTFExchange:    $EXCHANGE_ADDRESS"
echo "  SettlementVault: $VAULT_ADDRESS"
echo "  MarketFactory:  $MARKET_FACTORY_ADDRESS"
echo ""
echo "Test Accounts (funded with 10,000 USDC each):"
echo "  Account 0: 0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"
echo "  Account 1: 0x70997970C51812dc3A010C7d01b50e0d17dc79C8"
echo "  Account 2: 0x3C44CdDdB6a900fa2b585dd299e03d12FA4293BC"
echo "  Account 3: 0x90F79bf6EB2c4f870365E785982E1f101E93b906"
echo "  Account 4: 0x15d34AAf54267DB7D7c367839AAf71A00a2C6A65"
echo ""
echo "Environment files created:"
echo "  - $ENV_LOCAL_FILE"
echo "  - $BACKEND_ENV_FILE"
echo "  - $FRONTEND_ENV_FILE"
echo ""
if [ "$START_ANVIL" = true ]; then
    echo -e "${YELLOW}Anvil is running in background (PID: $(cat $ANVIL_PID_FILE))${NC}"
    echo "To stop: kill \$(cat $ANVIL_PID_FILE)"
fi
