/**
 * Contract ABIs for the on-chain settlement system
 * Generated from Foundry compiled contracts
 */

// Market Contract ABI
export const marketAbi = [
  {
    type: "constructor",
    inputs: [
      { name: "_conditionalTokens", type: "address", internalType: "address" },
      { name: "_collateralToken", type: "address", internalType: "address" },
      { name: "_oracle", type: "address", internalType: "address" },
      { name: "_feeRecipient", type: "address", internalType: "address" },
      { name: "_questionId", type: "bytes32", internalType: "bytes32" },
      { name: "_questionText", type: "string", internalType: "string" },
      { name: "_resolutionCriteriaText", type: "string", internalType: "string" },
      { name: "_endTime", type: "uint256", internalType: "uint256" },
    ],
    stateMutability: "nonpayable",
  },
  { type: "function", name: "BPS_DENOMINATOR", inputs: [], outputs: [{ name: "", type: "uint256", internalType: "uint256" }], stateMutability: "view" },
  { type: "function", name: "DISPUTE_PERIOD", inputs: [], outputs: [{ name: "", type: "uint256", internalType: "uint256" }], stateMutability: "view" },
  { type: "function", name: "PROTOCOL_FEE_BPS", inputs: [], outputs: [{ name: "", type: "uint256", internalType: "uint256" }], stateMutability: "view" },
  { type: "function", name: "collateralToken", inputs: [], outputs: [{ name: "", type: "address", internalType: "contract IERC20" }], stateMutability: "view" },
  { type: "function", name: "conditionId", inputs: [], outputs: [{ name: "", type: "bytes32", internalType: "bytes32" }], stateMutability: "view" },
  { type: "function", name: "conditionalTokens", inputs: [], outputs: [{ name: "", type: "address", internalType: "contract IConditionalTokens" }], stateMutability: "view" },
  { type: "function", name: "disputeEndTime", inputs: [], outputs: [{ name: "", type: "uint256", internalType: "uint256" }], stateMutability: "view" },
  { type: "function", name: "disputeResolution", inputs: [], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "endTime", inputs: [], outputs: [{ name: "", type: "uint256", internalType: "uint256" }], stateMutability: "view" },
  { type: "function", name: "feeRecipient", inputs: [], outputs: [{ name: "", type: "address", internalType: "address" }], stateMutability: "view" },
  { type: "function", name: "finalizeResolution", inputs: [], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "hasRedeemed", inputs: [{ name: "", type: "address", internalType: "address" }], outputs: [{ name: "", type: "bool", internalType: "bool" }], stateMutability: "view" },
  { type: "function", name: "mintTokens", inputs: [{ name: "collateralAmount", type: "uint256", internalType: "uint256" }], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "noTokenId", inputs: [], outputs: [{ name: "", type: "uint256", internalType: "uint256" }], stateMutability: "view" },
  { type: "function", name: "onERC1155BatchReceived", inputs: [{ name: "", type: "address", internalType: "address" }, { name: "", type: "address", internalType: "address" }, { name: "", type: "uint256[]", internalType: "uint256[]" }, { name: "", type: "uint256[]", internalType: "uint256[]" }, { name: "", type: "bytes", internalType: "bytes" }], outputs: [{ name: "", type: "bytes4", internalType: "bytes4" }], stateMutability: "pure" },
  { type: "function", name: "onERC1155Received", inputs: [{ name: "", type: "address", internalType: "address" }, { name: "", type: "address", internalType: "address" }, { name: "", type: "uint256", internalType: "uint256" }, { name: "", type: "uint256", internalType: "uint256" }, { name: "", type: "bytes", internalType: "bytes" }], outputs: [{ name: "", type: "bytes4", internalType: "bytes4" }], stateMutability: "pure" },
  { type: "function", name: "oracle", inputs: [], outputs: [{ name: "", type: "address", internalType: "address" }], stateMutability: "view" },
  { type: "function", name: "outcome", inputs: [], outputs: [{ name: "", type: "uint8", internalType: "enum IMarket.Outcome" }], stateMutability: "view" },
  { type: "function", name: "proposeResolution", inputs: [{ name: "_outcome", type: "uint8", internalType: "enum IMarket.Outcome" }], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "question", inputs: [], outputs: [{ name: "", type: "string", internalType: "string" }], stateMutability: "view" },
  { type: "function", name: "questionId", inputs: [], outputs: [{ name: "", type: "bytes32", internalType: "bytes32" }], stateMutability: "view" },
  { type: "function", name: "redeemTokens", inputs: [{ name: "amount", type: "uint256", internalType: "uint256" }], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "redeemWinnings", inputs: [], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "resolutionCriteria", inputs: [], outputs: [{ name: "", type: "string", internalType: "string" }], stateMutability: "view" },
  { type: "function", name: "resolutionTime", inputs: [], outputs: [{ name: "", type: "uint256", internalType: "uint256" }], stateMutability: "view" },
  { type: "function", name: "state", inputs: [], outputs: [{ name: "", type: "uint8", internalType: "enum IMarket.State" }], stateMutability: "view" },
  { type: "function", name: "supportsInterface", inputs: [{ name: "interfaceId", type: "bytes4", internalType: "bytes4" }], outputs: [{ name: "", type: "bool", internalType: "bool" }], stateMutability: "pure" },
  { type: "function", name: "totalFeesCollected", inputs: [], outputs: [{ name: "", type: "uint256", internalType: "uint256" }], stateMutability: "view" },
  { type: "function", name: "withdrawFees", inputs: [], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "yesTokenId", inputs: [], outputs: [{ name: "", type: "uint256", internalType: "uint256" }], stateMutability: "view" },
  { type: "event", name: "MarketResolved", inputs: [{ name: "outcome", type: "uint8", indexed: true, internalType: "enum IMarket.Outcome" }], anonymous: false },
  { type: "event", name: "ResolutionDisputed", inputs: [{ name: "disputer", type: "address", indexed: false, internalType: "address" }], anonymous: false },
  { type: "event", name: "ResolutionProposed", inputs: [{ name: "outcome", type: "uint8", indexed: true, internalType: "enum IMarket.Outcome" }, { name: "proposer", type: "address", indexed: false, internalType: "address" }], anonymous: false },
  { type: "event", name: "StateChanged", inputs: [{ name: "newState", type: "uint8", indexed: true, internalType: "enum IMarket.State" }], anonymous: false },
  { type: "event", name: "TokensMinted", inputs: [{ name: "user", type: "address", indexed: true, internalType: "address" }, { name: "amount", type: "uint256", indexed: false, internalType: "uint256" }], anonymous: false },
  { type: "event", name: "TokensRedeemed", inputs: [{ name: "user", type: "address", indexed: true, internalType: "address" }, { name: "yesAmount", type: "uint256", indexed: false, internalType: "uint256" }, { name: "noAmount", type: "uint256", indexed: false, internalType: "uint256" }], anonymous: false },
  { type: "event", name: "WinningsRedeemed", inputs: [{ name: "user", type: "address", indexed: true, internalType: "address" }, { name: "tokenType", type: "uint8", indexed: false, internalType: "enum IMarket.Outcome" }, { name: "payout", type: "uint256", indexed: false, internalType: "uint256" }], anonymous: false },
  { type: "error", name: "AlreadyRedeemed", inputs: [] },
  { type: "error", name: "DisputePeriodEnded", inputs: [] },
  { type: "error", name: "DisputePeriodNotEnded", inputs: [] },
  { type: "error", name: "InsufficientTokenBalance", inputs: [{ name: "required", type: "uint256", internalType: "uint256" }, { name: "available", type: "uint256", internalType: "uint256" }] },
  { type: "error", name: "InvalidEndTime", inputs: [] },
  { type: "error", name: "InvalidOutcome", inputs: [] },
  { type: "error", name: "MarketAlreadyResolved", inputs: [] },
  { type: "error", name: "MarketEndTimeNotReached", inputs: [] },
  { type: "error", name: "MarketNotActive", inputs: [] },
  { type: "error", name: "MarketNotDisputed", inputs: [] },
  { type: "error", name: "MarketNotPendingResolution", inputs: [] },
  { type: "error", name: "MarketNotResolved", inputs: [] },
  { type: "error", name: "NoWinningTokens", inputs: [] },
  { type: "error", name: "ReentrancyGuardReentrantCall", inputs: [] },
  { type: "error", name: "SafeERC20FailedOperation", inputs: [{ name: "token", type: "address", internalType: "address" }] },
  { type: "error", name: "TokenAmountMismatch", inputs: [{ name: "yesAmount", type: "uint256", internalType: "uint256" }, { name: "noAmount", type: "uint256", internalType: "uint256" }] },
  { type: "error", name: "UnauthorizedOracle", inputs: [] },
  { type: "error", name: "ZeroAmount", inputs: [] },
] as const;


// MarketFactory Contract ABI
export const marketFactoryAbi = [
  {
    type: "constructor",
    inputs: [
      { name: "_conditionalTokensAddr", type: "address", internalType: "address" },
      { name: "_collateralTokenAddr", type: "address", internalType: "address" },
      { name: "_oracle", type: "address", internalType: "address" },
      { name: "_feeRecipient", type: "address", internalType: "address" },
    ],
    stateMutability: "nonpayable",
  },
  { type: "function", name: "MIN_INITIAL_LIQUIDITY", inputs: [], outputs: [{ name: "", type: "uint256", internalType: "uint256" }], stateMutability: "view" },
  { type: "function", name: "allMarkets", inputs: [], outputs: [{ name: "", type: "address[]", internalType: "address[]" }], stateMutability: "view" },
  { type: "function", name: "collateralToken", inputs: [], outputs: [{ name: "", type: "address", internalType: "address" }], stateMutability: "view" },
  { type: "function", name: "conditionalTokens", inputs: [], outputs: [{ name: "", type: "address", internalType: "address" }], stateMutability: "view" },
  { type: "function", name: "createMarket", inputs: [{ name: "question", type: "string", internalType: "string" }, { name: "resolutionCriteria", type: "string", internalType: "string" }, { name: "endTime", type: "uint256", internalType: "uint256" }, { name: "initialLiquidity", type: "uint256", internalType: "uint256" }], outputs: [{ name: "market", type: "address", internalType: "address" }], stateMutability: "nonpayable" },
  { type: "function", name: "feeRecipient", inputs: [], outputs: [{ name: "", type: "address", internalType: "address" }], stateMutability: "view" },
  { type: "function", name: "marketCount", inputs: [], outputs: [{ name: "", type: "uint256", internalType: "uint256" }], stateMutability: "view" },
  { type: "function", name: "markets", inputs: [{ name: "questionId", type: "bytes32", internalType: "bytes32" }], outputs: [{ name: "", type: "address", internalType: "address" }], stateMutability: "view" },
  { type: "function", name: "minInitialLiquidity", inputs: [], outputs: [{ name: "", type: "uint256", internalType: "uint256" }], stateMutability: "pure" },
  { type: "function", name: "onERC1155BatchReceived", inputs: [{ name: "", type: "address", internalType: "address" }, { name: "", type: "address", internalType: "address" }, { name: "", type: "uint256[]", internalType: "uint256[]" }, { name: "", type: "uint256[]", internalType: "uint256[]" }, { name: "", type: "bytes", internalType: "bytes" }], outputs: [{ name: "", type: "bytes4", internalType: "bytes4" }], stateMutability: "pure" },
  { type: "function", name: "onERC1155Received", inputs: [{ name: "", type: "address", internalType: "address" }, { name: "", type: "address", internalType: "address" }, { name: "", type: "uint256", internalType: "uint256" }, { name: "", type: "uint256", internalType: "uint256" }, { name: "", type: "bytes", internalType: "bytes" }], outputs: [{ name: "", type: "bytes4", internalType: "bytes4" }], stateMutability: "pure" },
  { type: "function", name: "oracle", inputs: [], outputs: [{ name: "", type: "address", internalType: "address" }], stateMutability: "view" },
  { type: "function", name: "owner", inputs: [], outputs: [{ name: "", type: "address", internalType: "address" }], stateMutability: "view" },
  { type: "function", name: "pause", inputs: [], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "paused", inputs: [], outputs: [{ name: "", type: "bool", internalType: "bool" }], stateMutability: "view" },
  { type: "function", name: "renounceOwnership", inputs: [], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "supportsInterface", inputs: [{ name: "interfaceId", type: "bytes4", internalType: "bytes4" }], outputs: [{ name: "", type: "bool", internalType: "bool" }], stateMutability: "pure" },
  { type: "function", name: "transferOwnership", inputs: [{ name: "newOwner", type: "address", internalType: "address" }], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "unpause", inputs: [], outputs: [], stateMutability: "nonpayable" },
  { type: "event", name: "MarketCreated", inputs: [{ name: "market", type: "address", indexed: true, internalType: "address" }, { name: "questionId", type: "bytes32", indexed: true, internalType: "bytes32" }, { name: "question", type: "string", indexed: false, internalType: "string" }, { name: "endTime", type: "uint256", indexed: false, internalType: "uint256" }, { name: "creator", type: "address", indexed: false, internalType: "address" }], anonymous: false },
  { type: "event", name: "OwnershipTransferred", inputs: [{ name: "previousOwner", type: "address", indexed: true, internalType: "address" }, { name: "newOwner", type: "address", indexed: true, internalType: "address" }], anonymous: false },
  { type: "event", name: "Paused", inputs: [{ name: "account", type: "address", indexed: false, internalType: "address" }], anonymous: false },
  { type: "event", name: "Unpaused", inputs: [{ name: "account", type: "address", indexed: false, internalType: "address" }], anonymous: false },
  { type: "error", name: "EmptyQuestion", inputs: [] },
  { type: "error", name: "EmptyResolutionCriteria", inputs: [] },
  { type: "error", name: "EnforcedPause", inputs: [] },
  { type: "error", name: "ExpectedPause", inputs: [] },
  { type: "error", name: "InsufficientInitialLiquidity", inputs: [{ name: "provided", type: "uint256", internalType: "uint256" }, { name: "minimum", type: "uint256", internalType: "uint256" }] },
  { type: "error", name: "InvalidEndDate", inputs: [{ name: "endDate", type: "uint256", internalType: "uint256" }, { name: "currentTime", type: "uint256", internalType: "uint256" }] },
  { type: "error", name: "MarketAlreadyExists", inputs: [{ name: "questionId", type: "bytes32", internalType: "bytes32" }] },
  { type: "error", name: "OwnableInvalidOwner", inputs: [{ name: "owner", type: "address", internalType: "address" }] },
  { type: "error", name: "OwnableUnauthorizedAccount", inputs: [{ name: "account", type: "address", internalType: "address" }] },
  { type: "error", name: "ReentrancyGuardReentrantCall", inputs: [] },
  { type: "error", name: "SafeERC20FailedOperation", inputs: [{ name: "token", type: "address", internalType: "address" }] },
] as const;


// OrderBook Contract ABI
export const orderBookAbi = [
  {
    type: "constructor",
    inputs: [
      { name: "conditionalTokensAddr", type: "address", internalType: "address" },
      { name: "collateralTokenAddr", type: "address", internalType: "address" },
    ],
    stateMutability: "nonpayable",
  },
  { type: "function", name: "BPS_DENOMINATOR", inputs: [], outputs: [{ name: "", type: "uint256", internalType: "uint256" }], stateMutability: "view" },
  { type: "function", name: "MAX_PRICE", inputs: [], outputs: [{ name: "", type: "uint256", internalType: "uint256" }], stateMutability: "view" },
  { type: "function", name: "MIN_PRICE", inputs: [], outputs: [{ name: "", type: "uint256", internalType: "uint256" }], stateMutability: "view" },
  { type: "function", name: "cancelOrder", inputs: [{ name: "orderId", type: "uint256", internalType: "uint256" }], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "collateralToken", inputs: [], outputs: [{ name: "", type: "address", internalType: "address" }], stateMutability: "view" },
  { type: "function", name: "conditionalTokens", inputs: [], outputs: [{ name: "", type: "address", internalType: "address" }], stateMutability: "view" },
  { type: "function", name: "getBestAsk", inputs: [{ name: "marketId", type: "bytes32", internalType: "bytes32" }, { name: "tokenId", type: "uint256", internalType: "uint256" }], outputs: [{ name: "price", type: "uint256", internalType: "uint256" }, { name: "quantity", type: "uint256", internalType: "uint256" }], stateMutability: "view" },
  { type: "function", name: "getBestBid", inputs: [{ name: "marketId", type: "bytes32", internalType: "bytes32" }, { name: "tokenId", type: "uint256", internalType: "uint256" }], outputs: [{ name: "price", type: "uint256", internalType: "uint256" }, { name: "quantity", type: "uint256", internalType: "uint256" }], stateMutability: "view" },
  {
    type: "function",
    name: "getOrderBook",
    inputs: [{ name: "marketId", type: "bytes32", internalType: "bytes32" }, { name: "tokenId", type: "uint256", internalType: "uint256" }, { name: "depth", type: "uint256", internalType: "uint256" }],
    outputs: [
      { name: "bids", type: "tuple[]", internalType: "struct IOrderBook.Order[]", components: [{ name: "id", type: "uint256", internalType: "uint256" }, { name: "maker", type: "address", internalType: "address" }, { name: "marketId", type: "bytes32", internalType: "bytes32" }, { name: "tokenId", type: "uint256", internalType: "uint256" }, { name: "side", type: "uint8", internalType: "enum IOrderBook.Side" }, { name: "price", type: "uint256", internalType: "uint256" }, { name: "quantity", type: "uint256", internalType: "uint256" }, { name: "filled", type: "uint256", internalType: "uint256" }, { name: "timestamp", type: "uint256", internalType: "uint256" }, { name: "active", type: "bool", internalType: "bool" }] },
      { name: "asks", type: "tuple[]", internalType: "struct IOrderBook.Order[]", components: [{ name: "id", type: "uint256", internalType: "uint256" }, { name: "maker", type: "address", internalType: "address" }, { name: "marketId", type: "bytes32", internalType: "bytes32" }, { name: "tokenId", type: "uint256", internalType: "uint256" }, { name: "side", type: "uint8", internalType: "enum IOrderBook.Side" }, { name: "price", type: "uint256", internalType: "uint256" }, { name: "quantity", type: "uint256", internalType: "uint256" }, { name: "filled", type: "uint256", internalType: "uint256" }, { name: "timestamp", type: "uint256", internalType: "uint256" }, { name: "active", type: "bool", internalType: "bool" }] },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getUserOrders",
    inputs: [{ name: "user", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "tuple[]", internalType: "struct IOrderBook.Order[]", components: [{ name: "id", type: "uint256", internalType: "uint256" }, { name: "maker", type: "address", internalType: "address" }, { name: "marketId", type: "bytes32", internalType: "bytes32" }, { name: "tokenId", type: "uint256", internalType: "uint256" }, { name: "side", type: "uint8", internalType: "enum IOrderBook.Side" }, { name: "price", type: "uint256", internalType: "uint256" }, { name: "quantity", type: "uint256", internalType: "uint256" }, { name: "filled", type: "uint256", internalType: "uint256" }, { name: "timestamp", type: "uint256", internalType: "uint256" }, { name: "active", type: "bool", internalType: "bool" }] }],
    stateMutability: "view",
  },
  { type: "function", name: "nextOrderId", inputs: [], outputs: [{ name: "", type: "uint256", internalType: "uint256" }], stateMutability: "view" },
  { type: "function", name: "onERC1155BatchReceived", inputs: [{ name: "", type: "address", internalType: "address" }, { name: "", type: "address", internalType: "address" }, { name: "", type: "uint256[]", internalType: "uint256[]" }, { name: "", type: "uint256[]", internalType: "uint256[]" }, { name: "", type: "bytes", internalType: "bytes" }], outputs: [{ name: "", type: "bytes4", internalType: "bytes4" }], stateMutability: "pure" },
  { type: "function", name: "onERC1155Received", inputs: [{ name: "", type: "address", internalType: "address" }, { name: "", type: "address", internalType: "address" }, { name: "", type: "uint256", internalType: "uint256" }, { name: "", type: "uint256", internalType: "uint256" }, { name: "", type: "bytes", internalType: "bytes" }], outputs: [{ name: "", type: "bytes4", internalType: "bytes4" }], stateMutability: "pure" },
  {
    type: "function",
    name: "orders",
    inputs: [{ name: "orderId", type: "uint256", internalType: "uint256" }],
    outputs: [{ name: "", type: "tuple", internalType: "struct IOrderBook.Order", components: [{ name: "id", type: "uint256", internalType: "uint256" }, { name: "maker", type: "address", internalType: "address" }, { name: "marketId", type: "bytes32", internalType: "bytes32" }, { name: "tokenId", type: "uint256", internalType: "uint256" }, { name: "side", type: "uint8", internalType: "enum IOrderBook.Side" }, { name: "price", type: "uint256", internalType: "uint256" }, { name: "quantity", type: "uint256", internalType: "uint256" }, { name: "filled", type: "uint256", internalType: "uint256" }, { name: "timestamp", type: "uint256", internalType: "uint256" }, { name: "active", type: "bool", internalType: "bool" }] }],
    stateMutability: "view",
  },
  { type: "function", name: "owner", inputs: [], outputs: [{ name: "", type: "address", internalType: "address" }], stateMutability: "view" },
  { type: "function", name: "pause", inputs: [], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "paused", inputs: [], outputs: [{ name: "", type: "bool", internalType: "bool" }], stateMutability: "view" },
  { type: "function", name: "placeOrder", inputs: [{ name: "marketId", type: "bytes32", internalType: "bytes32" }, { name: "tokenId", type: "uint256", internalType: "uint256" }, { name: "side", type: "uint8", internalType: "enum IOrderBook.Side" }, { name: "price", type: "uint256", internalType: "uint256" }, { name: "quantity", type: "uint256", internalType: "uint256" }], outputs: [{ name: "orderId", type: "uint256", internalType: "uint256" }], stateMutability: "nonpayable" },
  { type: "function", name: "renounceOwnership", inputs: [], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "supportsInterface", inputs: [{ name: "interfaceId", type: "bytes4", internalType: "bytes4" }], outputs: [{ name: "", type: "bool", internalType: "bool" }], stateMutability: "pure" },
  { type: "function", name: "transferOwnership", inputs: [{ name: "newOwner", type: "address", internalType: "address" }], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "unpause", inputs: [], outputs: [], stateMutability: "nonpayable" },
  { type: "event", name: "OrderCancelled", inputs: [{ name: "orderId", type: "uint256", indexed: true, internalType: "uint256" }], anonymous: false },
  { type: "event", name: "OrderFilled", inputs: [{ name: "orderId", type: "uint256", indexed: true, internalType: "uint256" }, { name: "taker", type: "address", indexed: true, internalType: "address" }, { name: "fillAmount", type: "uint256", indexed: false, internalType: "uint256" }, { name: "fillPrice", type: "uint256", indexed: false, internalType: "uint256" }], anonymous: false },
  { type: "event", name: "OrderPlaced", inputs: [{ name: "orderId", type: "uint256", indexed: true, internalType: "uint256" }, { name: "maker", type: "address", indexed: true, internalType: "address" }, { name: "marketId", type: "bytes32", indexed: true, internalType: "bytes32" }, { name: "tokenId", type: "uint256", indexed: false, internalType: "uint256" }, { name: "side", type: "uint8", indexed: false, internalType: "enum IOrderBook.Side" }, { name: "price", type: "uint256", indexed: false, internalType: "uint256" }, { name: "quantity", type: "uint256", indexed: false, internalType: "uint256" }], anonymous: false },
  { type: "event", name: "OwnershipTransferred", inputs: [{ name: "previousOwner", type: "address", indexed: true, internalType: "address" }, { name: "newOwner", type: "address", indexed: true, internalType: "address" }], anonymous: false },
  { type: "event", name: "Paused", inputs: [{ name: "account", type: "address", indexed: false, internalType: "address" }], anonymous: false },
  { type: "event", name: "Trade", inputs: [{ name: "marketId", type: "bytes32", indexed: true, internalType: "bytes32" }, { name: "tokenId", type: "uint256", indexed: true, internalType: "uint256" }, { name: "buyer", type: "address", indexed: false, internalType: "address" }, { name: "seller", type: "address", indexed: false, internalType: "address" }, { name: "price", type: "uint256", indexed: false, internalType: "uint256" }, { name: "quantity", type: "uint256", indexed: false, internalType: "uint256" }], anonymous: false },
  { type: "event", name: "Unpaused", inputs: [{ name: "account", type: "address", indexed: false, internalType: "address" }], anonymous: false },
  { type: "error", name: "EnforcedPause", inputs: [] },
  { type: "error", name: "ExpectedPause", inputs: [] },
  { type: "error", name: "InsufficientCollateral", inputs: [{ name: "required", type: "uint256", internalType: "uint256" }, { name: "available", type: "uint256", internalType: "uint256" }] },
  { type: "error", name: "InsufficientTokenBalance", inputs: [{ name: "required", type: "uint256", internalType: "uint256" }, { name: "available", type: "uint256", internalType: "uint256" }] },
  { type: "error", name: "InvalidMarket", inputs: [] },
  { type: "error", name: "InvalidPrice", inputs: [{ name: "price", type: "uint256", internalType: "uint256" }] },
  { type: "error", name: "InvalidQuantity", inputs: [] },
  { type: "error", name: "MarketPaused", inputs: [] },
  { type: "error", name: "OrderNotActive", inputs: [{ name: "orderId", type: "uint256", internalType: "uint256" }] },
  { type: "error", name: "OrderNotFound", inputs: [{ name: "orderId", type: "uint256", internalType: "uint256" }] },
  { type: "error", name: "OwnableInvalidOwner", inputs: [{ name: "owner", type: "address", internalType: "address" }] },
  { type: "error", name: "OwnableUnauthorizedAccount", inputs: [{ name: "account", type: "address", internalType: "address" }] },
  { type: "error", name: "ReentrancyGuardReentrantCall", inputs: [] },
  { type: "error", name: "SafeERC20FailedOperation", inputs: [{ name: "token", type: "address", internalType: "address" }] },
  { type: "error", name: "UnauthorizedCancellation", inputs: [{ name: "caller", type: "address", internalType: "address" }, { name: "maker", type: "address", internalType: "address" }] },
] as const;


// ConditionalTokens Contract ABI (ERC-1155)
export const conditionalTokensAbi = [
  { type: "constructor", inputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "balanceOf", inputs: [{ name: "account", type: "address", internalType: "address" }, { name: "id", type: "uint256", internalType: "uint256" }], outputs: [{ name: "", type: "uint256", internalType: "uint256" }], stateMutability: "view" },
  { type: "function", name: "balanceOfBatch", inputs: [{ name: "accounts", type: "address[]", internalType: "address[]" }, { name: "ids", type: "uint256[]", internalType: "uint256[]" }], outputs: [{ name: "", type: "uint256[]", internalType: "uint256[]" }], stateMutability: "view" },
  { type: "function", name: "getCollectionId", inputs: [{ name: "parentCollectionId", type: "bytes32", internalType: "bytes32" }, { name: "conditionId", type: "bytes32", internalType: "bytes32" }, { name: "indexSet", type: "uint256", internalType: "uint256" }], outputs: [{ name: "", type: "bytes32", internalType: "bytes32" }], stateMutability: "pure" },
  { type: "function", name: "getConditionId", inputs: [{ name: "oracle", type: "address", internalType: "address" }, { name: "questionId", type: "bytes32", internalType: "bytes32" }, { name: "outcomeSlotCount", type: "uint256", internalType: "uint256" }], outputs: [{ name: "", type: "bytes32", internalType: "bytes32" }], stateMutability: "pure" },
  { type: "function", name: "getOutcomeSlotCount", inputs: [{ name: "conditionId", type: "bytes32", internalType: "bytes32" }], outputs: [{ name: "", type: "uint256", internalType: "uint256" }], stateMutability: "view" },
  { type: "function", name: "getPositionId", inputs: [{ name: "collateralToken", type: "address", internalType: "contract IERC20" }, { name: "collectionId", type: "bytes32", internalType: "bytes32" }], outputs: [{ name: "", type: "uint256", internalType: "uint256" }], stateMutability: "pure" },
  { type: "function", name: "isApprovedForAll", inputs: [{ name: "account", type: "address", internalType: "address" }, { name: "operator", type: "address", internalType: "address" }], outputs: [{ name: "", type: "bool", internalType: "bool" }], stateMutability: "view" },
  { type: "function", name: "mergePositions", inputs: [{ name: "collateralToken", type: "address", internalType: "contract IERC20" }, { name: "parentCollectionId", type: "bytes32", internalType: "bytes32" }, { name: "conditionId", type: "bytes32", internalType: "bytes32" }, { name: "partition", type: "uint256[]", internalType: "uint256[]" }, { name: "amount", type: "uint256", internalType: "uint256" }], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "payoutDenominator", inputs: [{ name: "conditionId", type: "bytes32", internalType: "bytes32" }], outputs: [{ name: "", type: "uint256", internalType: "uint256" }], stateMutability: "view" },
  { type: "function", name: "payoutNumerators", inputs: [{ name: "conditionId", type: "bytes32", internalType: "bytes32" }, { name: "index", type: "uint256", internalType: "uint256" }], outputs: [{ name: "", type: "uint256", internalType: "uint256" }], stateMutability: "view" },
  { type: "function", name: "prepareCondition", inputs: [{ name: "oracle", type: "address", internalType: "address" }, { name: "questionId", type: "bytes32", internalType: "bytes32" }, { name: "outcomeSlotCount", type: "uint256", internalType: "uint256" }], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "redeemPositions", inputs: [{ name: "collateralToken", type: "address", internalType: "contract IERC20" }, { name: "parentCollectionId", type: "bytes32", internalType: "bytes32" }, { name: "conditionId", type: "bytes32", internalType: "bytes32" }, { name: "indexSets", type: "uint256[]", internalType: "uint256[]" }], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "reportPayouts", inputs: [{ name: "questionId", type: "bytes32", internalType: "bytes32" }, { name: "payouts", type: "uint256[]", internalType: "uint256[]" }], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "safeBatchTransferFrom", inputs: [{ name: "from", type: "address", internalType: "address" }, { name: "to", type: "address", internalType: "address" }, { name: "ids", type: "uint256[]", internalType: "uint256[]" }, { name: "values", type: "uint256[]", internalType: "uint256[]" }, { name: "data", type: "bytes", internalType: "bytes" }], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "safeTransferFrom", inputs: [{ name: "from", type: "address", internalType: "address" }, { name: "to", type: "address", internalType: "address" }, { name: "id", type: "uint256", internalType: "uint256" }, { name: "value", type: "uint256", internalType: "uint256" }, { name: "data", type: "bytes", internalType: "bytes" }], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "setApprovalForAll", inputs: [{ name: "operator", type: "address", internalType: "address" }, { name: "approved", type: "bool", internalType: "bool" }], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "splitPosition", inputs: [{ name: "collateralToken", type: "address", internalType: "contract IERC20" }, { name: "parentCollectionId", type: "bytes32", internalType: "bytes32" }, { name: "conditionId", type: "bytes32", internalType: "bytes32" }, { name: "partition", type: "uint256[]", internalType: "uint256[]" }, { name: "amount", type: "uint256", internalType: "uint256" }], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "supportsInterface", inputs: [{ name: "interfaceId", type: "bytes4", internalType: "bytes4" }], outputs: [{ name: "", type: "bool", internalType: "bool" }], stateMutability: "view" },
  { type: "function", name: "totalSupply", inputs: [{ name: "positionId", type: "uint256", internalType: "uint256" }], outputs: [{ name: "", type: "uint256", internalType: "uint256" }], stateMutability: "view" },
  { type: "function", name: "uri", inputs: [{ name: "", type: "uint256", internalType: "uint256" }], outputs: [{ name: "", type: "string", internalType: "string" }], stateMutability: "view" },
  { type: "event", name: "ApprovalForAll", inputs: [{ name: "account", type: "address", indexed: true, internalType: "address" }, { name: "operator", type: "address", indexed: true, internalType: "address" }, { name: "approved", type: "bool", indexed: false, internalType: "bool" }], anonymous: false },
  { type: "event", name: "ConditionPreparation", inputs: [{ name: "conditionId", type: "bytes32", indexed: true, internalType: "bytes32" }, { name: "oracle", type: "address", indexed: true, internalType: "address" }, { name: "questionId", type: "bytes32", indexed: true, internalType: "bytes32" }, { name: "outcomeSlotCount", type: "uint256", indexed: false, internalType: "uint256" }], anonymous: false },
  { type: "event", name: "ConditionResolution", inputs: [{ name: "conditionId", type: "bytes32", indexed: true, internalType: "bytes32" }, { name: "oracle", type: "address", indexed: true, internalType: "address" }, { name: "questionId", type: "bytes32", indexed: true, internalType: "bytes32" }, { name: "outcomeSlotCount", type: "uint256", indexed: false, internalType: "uint256" }, { name: "payoutNumerators", type: "uint256[]", indexed: false, internalType: "uint256[]" }], anonymous: false },
  { type: "event", name: "PayoutRedemption", inputs: [{ name: "redeemer", type: "address", indexed: true, internalType: "address" }, { name: "collateralToken", type: "address", indexed: true, internalType: "contract IERC20" }, { name: "parentCollectionId", type: "bytes32", indexed: true, internalType: "bytes32" }, { name: "conditionId", type: "bytes32", indexed: false, internalType: "bytes32" }, { name: "indexSets", type: "uint256[]", indexed: false, internalType: "uint256[]" }, { name: "payout", type: "uint256", indexed: false, internalType: "uint256" }], anonymous: false },
  { type: "event", name: "PositionSplit", inputs: [{ name: "stakeholder", type: "address", indexed: true, internalType: "address" }, { name: "collateralToken", type: "address", indexed: false, internalType: "contract IERC20" }, { name: "parentCollectionId", type: "bytes32", indexed: true, internalType: "bytes32" }, { name: "conditionId", type: "bytes32", indexed: true, internalType: "bytes32" }, { name: "partition", type: "uint256[]", indexed: false, internalType: "uint256[]" }, { name: "amount", type: "uint256", indexed: false, internalType: "uint256" }], anonymous: false },
  { type: "event", name: "PositionsMerge", inputs: [{ name: "stakeholder", type: "address", indexed: true, internalType: "address" }, { name: "collateralToken", type: "address", indexed: false, internalType: "contract IERC20" }, { name: "parentCollectionId", type: "bytes32", indexed: true, internalType: "bytes32" }, { name: "conditionId", type: "bytes32", indexed: true, internalType: "bytes32" }, { name: "partition", type: "uint256[]", indexed: false, internalType: "uint256[]" }, { name: "amount", type: "uint256", indexed: false, internalType: "uint256" }], anonymous: false },
  { type: "event", name: "TransferBatch", inputs: [{ name: "operator", type: "address", indexed: true, internalType: "address" }, { name: "from", type: "address", indexed: true, internalType: "address" }, { name: "to", type: "address", indexed: true, internalType: "address" }, { name: "ids", type: "uint256[]", indexed: false, internalType: "uint256[]" }, { name: "values", type: "uint256[]", indexed: false, internalType: "uint256[]" }], anonymous: false },
  { type: "event", name: "TransferSingle", inputs: [{ name: "operator", type: "address", indexed: true, internalType: "address" }, { name: "from", type: "address", indexed: true, internalType: "address" }, { name: "to", type: "address", indexed: true, internalType: "address" }, { name: "id", type: "uint256", indexed: false, internalType: "uint256" }, { name: "value", type: "uint256", indexed: false, internalType: "uint256" }], anonymous: false },
  { type: "event", name: "URI", inputs: [{ name: "value", type: "string", indexed: false, internalType: "string" }, { name: "id", type: "uint256", indexed: true, internalType: "uint256" }], anonymous: false },
  { type: "error", name: "ConditionAlreadyPrepared", inputs: [] },
  { type: "error", name: "ConditionAlreadyResolved", inputs: [] },
  { type: "error", name: "ConditionNotPrepared", inputs: [] },
  { type: "error", name: "ConditionNotResolved", inputs: [] },
  { type: "error", name: "ERC1155InsufficientBalance", inputs: [{ name: "sender", type: "address", internalType: "address" }, { name: "balance", type: "uint256", internalType: "uint256" }, { name: "needed", type: "uint256", internalType: "uint256" }, { name: "tokenId", type: "uint256", internalType: "uint256" }] },
  { type: "error", name: "ERC1155InvalidApprover", inputs: [{ name: "approver", type: "address", internalType: "address" }] },
  { type: "error", name: "ERC1155InvalidArrayLength", inputs: [{ name: "idsLength", type: "uint256", internalType: "uint256" }, { name: "valuesLength", type: "uint256", internalType: "uint256" }] },
  { type: "error", name: "ERC1155InvalidOperator", inputs: [{ name: "operator", type: "address", internalType: "address" }] },
  { type: "error", name: "ERC1155InvalidReceiver", inputs: [{ name: "receiver", type: "address", internalType: "address" }] },
  { type: "error", name: "ERC1155InvalidSender", inputs: [{ name: "sender", type: "address", internalType: "address" }] },
  { type: "error", name: "ERC1155MissingApprovalForAll", inputs: [{ name: "operator", type: "address", internalType: "address" }, { name: "owner", type: "address", internalType: "address" }] },
  { type: "error", name: "InvalidIndexSet", inputs: [] },
  { type: "error", name: "InvalidPartition", inputs: [] },
  { type: "error", name: "PartitionNotDisjoint", inputs: [] },
  { type: "error", name: "PayoutAllZeroes", inputs: [] },
  { type: "error", name: "PayoutNumeratorAlreadySet", inputs: [] },
  { type: "error", name: "ReentrancyGuardReentrantCall", inputs: [] },
  { type: "error", name: "SafeERC20FailedOperation", inputs: [{ name: "token", type: "address", internalType: "address" }] },
  { type: "error", name: "TooFewOutcomeSlots", inputs: [] },
  { type: "error", name: "TooManyOutcomeSlots", inputs: [] },
  { type: "error", name: "ZeroAmount", inputs: [] },
] as const;

// ERC20 ABI (for USDC interactions)
export const erc20Abi = [
  { type: "function", name: "allowance", inputs: [{ name: "owner", type: "address", internalType: "address" }, { name: "spender", type: "address", internalType: "address" }], outputs: [{ name: "", type: "uint256", internalType: "uint256" }], stateMutability: "view" },
  { type: "function", name: "approve", inputs: [{ name: "spender", type: "address", internalType: "address" }, { name: "value", type: "uint256", internalType: "uint256" }], outputs: [{ name: "", type: "bool", internalType: "bool" }], stateMutability: "nonpayable" },
  { type: "function", name: "balanceOf", inputs: [{ name: "account", type: "address", internalType: "address" }], outputs: [{ name: "", type: "uint256", internalType: "uint256" }], stateMutability: "view" },
  { type: "function", name: "decimals", inputs: [], outputs: [{ name: "", type: "uint8", internalType: "uint8" }], stateMutability: "view" },
  { type: "function", name: "name", inputs: [], outputs: [{ name: "", type: "string", internalType: "string" }], stateMutability: "view" },
  { type: "function", name: "symbol", inputs: [], outputs: [{ name: "", type: "string", internalType: "string" }], stateMutability: "view" },
  { type: "function", name: "totalSupply", inputs: [], outputs: [{ name: "", type: "uint256", internalType: "uint256" }], stateMutability: "view" },
  { type: "function", name: "transfer", inputs: [{ name: "to", type: "address", internalType: "address" }, { name: "value", type: "uint256", internalType: "uint256" }], outputs: [{ name: "", type: "bool", internalType: "bool" }], stateMutability: "nonpayable" },
  { type: "function", name: "transferFrom", inputs: [{ name: "from", type: "address", internalType: "address" }, { name: "to", type: "address", internalType: "address" }, { name: "value", type: "uint256", internalType: "uint256" }], outputs: [{ name: "", type: "bool", internalType: "bool" }], stateMutability: "nonpayable" },
  { type: "event", name: "Approval", inputs: [{ name: "owner", type: "address", indexed: true, internalType: "address" }, { name: "spender", type: "address", indexed: true, internalType: "address" }, { name: "value", type: "uint256", indexed: false, internalType: "uint256" }], anonymous: false },
  { type: "event", name: "Transfer", inputs: [{ name: "from", type: "address", indexed: true, internalType: "address" }, { name: "to", type: "address", indexed: true, internalType: "address" }, { name: "value", type: "uint256", indexed: false, internalType: "uint256" }], anonymous: false },
] as const;
