/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsersUserIdRouteImport } from './routes/users.$userId'
import { Route as DebatesNewRouteImport } from './routes/debates.new'
import { Route as DebatesDebateIdRouteImport } from './routes/debates.$debateId'
import { Route as AuthPathnameRouteImport } from './routes/auth.$pathname'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersUserIdRoute = UsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const DebatesNewRoute = DebatesNewRouteImport.update({
  id: '/debates/new',
  path: '/debates/new',
  getParentRoute: () => rootRouteImport,
} as any)
const DebatesDebateIdRoute = DebatesDebateIdRouteImport.update({
  id: '/debates/$debateId',
  path: '/debates/$debateId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthPathnameRoute = AuthPathnameRouteImport.update({
  id: '/auth/$pathname',
  path: '/auth/$pathname',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/$pathname': typeof AuthPathnameRoute
  '/debates/$debateId': typeof DebatesDebateIdRoute
  '/debates/new': typeof DebatesNewRoute
  '/users/$userId': typeof UsersUserIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/$pathname': typeof AuthPathnameRoute
  '/debates/$debateId': typeof DebatesDebateIdRoute
  '/debates/new': typeof DebatesNewRoute
  '/users/$userId': typeof UsersUserIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth/$pathname': typeof AuthPathnameRoute
  '/debates/$debateId': typeof DebatesDebateIdRoute
  '/debates/new': typeof DebatesNewRoute
  '/users/$userId': typeof UsersUserIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/$pathname'
    | '/debates/$debateId'
    | '/debates/new'
    | '/users/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/$pathname'
    | '/debates/$debateId'
    | '/debates/new'
    | '/users/$userId'
  id:
    | '__root__'
    | '/'
    | '/auth/$pathname'
    | '/debates/$debateId'
    | '/debates/new'
    | '/users/$userId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthPathnameRoute: typeof AuthPathnameRoute
  DebatesDebateIdRoute: typeof DebatesDebateIdRoute
  DebatesNewRoute: typeof DebatesNewRoute
  UsersUserIdRoute: typeof UsersUserIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/$userId': {
      id: '/users/$userId'
      path: '/users/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof UsersUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debates/new': {
      id: '/debates/new'
      path: '/debates/new'
      fullPath: '/debates/new'
      preLoaderRoute: typeof DebatesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debates/$debateId': {
      id: '/debates/$debateId'
      path: '/debates/$debateId'
      fullPath: '/debates/$debateId'
      preLoaderRoute: typeof DebatesDebateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/$pathname': {
      id: '/auth/$pathname'
      path: '/auth/$pathname'
      fullPath: '/auth/$pathname'
      preLoaderRoute: typeof AuthPathnameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthPathnameRoute: AuthPathnameRoute,
  DebatesDebateIdRoute: DebatesDebateIdRoute,
  DebatesNewRoute: DebatesNewRoute,
  UsersUserIdRoute: UsersUserIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
