/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MarketsMarketIdRouteImport } from './routes/markets.$marketId'
import { Route as AuthPathnameRouteImport } from './routes/auth.$pathname'

const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketsMarketIdRoute = MarketsMarketIdRouteImport.update({
  id: '/markets/$marketId',
  path: '/markets/$marketId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthPathnameRoute = AuthPathnameRouteImport.update({
  id: '/auth/$pathname',
  path: '/auth/$pathname',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/portfolio': typeof PortfolioRoute
  '/auth/$pathname': typeof AuthPathnameRoute
  '/markets/$marketId': typeof MarketsMarketIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/portfolio': typeof PortfolioRoute
  '/auth/$pathname': typeof AuthPathnameRoute
  '/markets/$marketId': typeof MarketsMarketIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/portfolio': typeof PortfolioRoute
  '/auth/$pathname': typeof AuthPathnameRoute
  '/markets/$marketId': typeof MarketsMarketIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/portfolio' | '/auth/$pathname' | '/markets/$marketId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/portfolio' | '/auth/$pathname' | '/markets/$marketId'
  id: '__root__' | '/' | '/portfolio' | '/auth/$pathname' | '/markets/$marketId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PortfolioRoute: typeof PortfolioRoute
  AuthPathnameRoute: typeof AuthPathnameRoute
  MarketsMarketIdRoute: typeof MarketsMarketIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/markets/$marketId': {
      id: '/markets/$marketId'
      path: '/markets/$marketId'
      fullPath: '/markets/$marketId'
      preLoaderRoute: typeof MarketsMarketIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/$pathname': {
      id: '/auth/$pathname'
      path: '/auth/$pathname'
      fullPath: '/auth/$pathname'
      preLoaderRoute: typeof AuthPathnameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PortfolioRoute: PortfolioRoute,
  AuthPathnameRoute: AuthPathnameRoute,
  MarketsMarketIdRoute: MarketsMarketIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
